export const airports = [
    {
      "code": "PAP",
      "lat": "36.4215",
      "lng": "-83.3607",
      "name": "",
      "city": "Port Au Prince",
      "state": "Ouest",
      "country": "Haiti",
      "woeid": "96110",
      "tz": "America/Port-au-Prince",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9974",
      "elev": "109",
      "icao": "MTPP",
      "direct_flights": "12",
      "carriers": "11"
    },
    {
      "code": "GOA",
      "lat": "44.4119",
      "lng": "8.84633",
      "name": "Genoa Cristoforo Colombo Airport",
      "city": "Genoa",
      "state": "Liguria",
      "country": "Italy",
      "woeid": "12513821",
      "tz": "Europe/Rome",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "http://www.aeroportodigenova.com/home/index.php",
      "runway_length": "9925",
      "elev": "10",
      "icao": "LIMJ",
      "direct_flights": "16",
      "carriers": "22"
    },
    {
      "code": "TXL",
      "lat": "52.5548",
      "lng": "13.289",
      "name": "Berlin-Tegel International Airport",
      "city": "Berlin",
      "state": "Berlin",
      "country": "Germany",
      "woeid": "22164086",
      "tz": "Europe/Berlin",
      "phone": "0180 5000 186 (0,12 Euro",
      "type": "Airports",
      "email": "",
      "url": "http://www.berlin-airport.de/PubEnglish/PubTegel/index.php?",
      "runway_length": "9918",
      "elev": "121",
      "icao": "EDDT",
      "direct_flights": "101",
      "carriers": "70"
    },
    {
      "code": "LUF",
      "lat": "33.5355",
      "lng": "-112.372",
      "name": "Luke Air Force Base",
      "city": "Webb",
      "state": "Arizona",
      "country": "United States",
      "woeid": "12520723",
      "tz": "America/Phoenix",
      "phone": "623 856 6376",
      "type": "Military Airport",
      "email": "",
      "url": "",
      "runway_length": "9910",
      "elev": "1085",
      "icao": "KLUF",
      "direct_flights": "0",
      "carriers": "0"
    },
    {
      "code": "ALP",
      "lat": "36.1808",
      "lng": "37.2267",
      "name": "Aleppo International Airport",
      "city": "Djibrine",
      "state": "H'alab",
      "country": "Syria",
      "woeid": "12517695",
      "tz": "Asia/Damascus",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9908",
      "elev": "1276",
      "icao": "OSAP",
      "direct_flights": "19",
      "carriers": "13"
    },
    {
      "code": "KLX",
      "lat": "37.0678",
      "lng": "22.0267",
      "name": "Kalamata Airport",
      "city": "Kalamae",
      "state": "Peloponnisos",
      "country": "Greece",
      "woeid": "12513292",
      "tz": "Europe/Athens",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9894",
      "elev": "20",
      "icao": "",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "CFE",
      "lat": "45.7896",
      "lng": "3.16013",
      "name": "Aulnat Airport",
      "city": "Aulnat",
      "state": "Auvergne",
      "country": "France",
      "woeid": "12512847",
      "tz": "Europe/Paris",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9892",
      "elev": "1089",
      "icao": "LFLC",
      "direct_flights": "19",
      "carriers": "7"
    },
    {
      "code": "MDZ",
      "lat": "-32.8319",
      "lng": "-68.7847",
      "name": "El Plumerillo Airport",
      "city": "Mendoza",
      "state": "Mendoza",
      "country": "Argentina",
      "woeid": "12510491",
      "tz": "America/Buenos_Aires",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9885",
      "elev": "2312",
      "icao": "KMDZ",
      "direct_flights": "2",
      "carriers": "4"
    },
    {
      "code": "SJO",
      "lat": "9.9919",
      "lng": "-84.2114",
      "name": "Juan Santamaria International Airport",
      "city": "Heredia",
      "state": "Alajuela",
      "country": "Costa Rica",
      "woeid": "12512434",
      "tz": "America/Costa_Rica",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9882",
      "elev": "3046",
      "icao": "MROC",
      "direct_flights": "42",
      "carriers": "28"
    },
    {
      "code": "BUD",
      "lat": "47.4453",
      "lng": "19.2195",
      "name": "Ferihegy Airport",
      "city": "Budapest",
      "state": "Budapest",
      "country": "Hungary",
      "woeid": "12513389",
      "tz": "Europe/Budapest",
      "phone": "(36) 1 2969696",
      "type": "Airports",
      "email": "",
      "url": "http://www.bud.hu",
      "runway_length": "9875",
      "elev": "440",
      "icao": "LHBP",
      "direct_flights": "102",
      "carriers": "64"
    },
    {
      "code": "REC",
      "lat": "-8.1261",
      "lng": "-34.9225",
      "name": "Gilberto Freyre International Airport",
      "city": "Recife",
      "state": "Pernambuco",
      "country": "Brazil",
      "woeid": "12511167",
      "tz": "America/Belem",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9875",
      "elev": "36",
      "icao": "SBRF",
      "direct_flights": "18",
      "carriers": "13"
    },
    {
      "code": "SSA",
      "lat": "-12.9081",
      "lng": "-38.3222",
      "name": "Deputado Luis Eduardo Magalhaes International Ai",
      "city": "Salvador",
      "state": "Nordeste",
      "country": "Brazil",
      "woeid": "12511112",
      "tz": "America/Belem",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9865",
      "elev": "60",
      "icao": "SBSV",
      "direct_flights": "24",
      "carriers": "14"
    },
    {
      "code": "WAW",
      "lat": "52.17",
      "lng": "20.9725",
      "name": "Okecie International Airport",
      "city": "Warsaw",
      "state": "Mazowieckie",
      "country": "Poland",
      "woeid": "12515363",
      "tz": "Europe/Warsaw",
      "phone": "+48 (22) 650 42 20",
      "type": "Airports",
      "email": "",
      "url": "http://www.lotnisko-chopina.pl/",
      "runway_length": "9852",
      "elev": "354",
      "icao": "EPWA",
      "direct_flights": "102",
      "carriers": "60"
    },
    {
      "code": "GBE",
      "lat": "-24.5558",
      "lng": "25.9189",
      "name": "Sir Seretse Khama International Airport",
      "city": "Tlokweng",
      "state": "South-East",
      "country": "Botswana",
      "woeid": "12510841",
      "tz": "Africa/Gaborone",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9850",
      "elev": "3299",
      "icao": "FBSK",
      "direct_flights": "5",
      "carriers": "2"
    },
    {
      "code": "UBP",
      "lat": "15.2489",
      "lng": "104.873",
      "name": "Ubon Airport",
      "city": "Don Mot Daeng",
      "state": "Ubon Ratchathani",
      "country": "Thailand",
      "woeid": "12517791",
      "tz": "Asia/Bangkok",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9848",
      "elev": "406",
      "icao": "",
      "direct_flights": "2",
      "carriers": "3"
    },
    {
      "code": "EIN",
      "lat": "51.4463",
      "lng": "5.39212",
      "name": "Eindhoven Airport",
      "city": "Eindhoven",
      "state": "North Brabant",
      "country": "Netherlands",
      "woeid": "12515087",
      "tz": "Europe/Amsterdam",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "http://www.eindhovenairport.com/",
      "runway_length": "9846",
      "elev": "74",
      "icao": "EHEH",
      "direct_flights": "21",
      "carriers": "9"
    },
    {
      "code": "KUF",
      "lat": "53.5067",
      "lng": "50.166",
      "name": "Kurumoch Airport",
      "city": "Syzran'",
      "state": "Samarskaya Oblast",
      "country": "Russia",
      "woeid": "12516311",
      "tz": "Europe/Samara",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9846",
      "elev": "479",
      "icao": "",
      "direct_flights": "34",
      "carriers": "22"
    },
    {
      "code": "KNH",
      "lat": "24.4583",
      "lng": "118.376",
      "name": "Kinmen County",
      "city": "Kinmen",
      "state": "Fujian",
      "country": "Taiwan",
      "woeid": "28760735",
      "tz": "Asia/Taipei",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9845",
      "elev": "30",
      "icao": "",
      "direct_flights": "5",
      "carriers": "3"
    },
    {
      "code": "AAE",
      "lat": "36.8236",
      "lng": "7.8103",
      "name": "El Mellah Airport",
      "city": "El Tarf",
      "state": "Annaba",
      "country": "Algeria",
      "woeid": "12510325",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "16",
      "icao": "DABB",
      "direct_flights": "6",
      "carriers": "2"
    },
    {
      "code": "AQJ",
      "lat": "29.6119",
      "lng": "35.0178",
      "name": "Aqaba International Airport",
      "city": "Aqaba",
      "state": "Al `Aqabah",
      "country": "Jordan",
      "woeid": "12514051",
      "tz": "Asia/Amman",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "174",
      "icao": "OJAQ",
      "direct_flights": "10",
      "carriers": "5"
    },
    {
      "code": "ASM",
      "lat": "15.2906",
      "lng": "38.9103",
      "name": "Yohannes Iv International Airport",
      "city": "Asmara",
      "state": "Maekel",
      "country": "Eritrea",
      "woeid": "12512750",
      "tz": "Africa/Asmara",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "7661",
      "icao": "HHAS",
      "direct_flights": "9",
      "carriers": "7"
    },
    {
      "code": "ATR",
      "lat": "20.5067",
      "lng": "-13.0436",
      "name": "Atar Airport",
      "city": "Atar",
      "state": "Adrar",
      "country": "Mauritania",
      "woeid": "12514800",
      "tz": "Africa/Nouakchott",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "758",
      "icao": "GQPA",
      "direct_flights": "2",
      "carriers": "1"
    },
    {
      "code": "ATZ",
      "lat": "27.0411",
      "lng": "31.0114",
      "name": "Asyut Airport",
      "city": "Asyut",
      "state": "Asyut",
      "country": "Egypt",
      "woeid": "12512667",
      "tz": "Africa/Cairo",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "774",
      "icao": "HEAT",
      "direct_flights": "5",
      "carriers": "5"
    },
    {
      "code": "AZR",
      "lat": "27.8378",
      "lng": "-0.1864",
      "name": "Touat Airport",
      "city": "Adrar",
      "state": "Adrar",
      "country": "Algeria",
      "woeid": "12510355",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "915",
      "icao": "DAUA",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "BAQ",
      "lat": "10.8961",
      "lng": "-74.7789",
      "name": "Ernesto Cortissoz Airport",
      "city": "Soledad",
      "state": "Atlantico",
      "country": "Colombia",
      "woeid": "12512376",
      "tz": "America/Bogota",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "94",
      "icao": "SKBQ",
      "direct_flights": "15",
      "carriers": "9"
    },
    {
      "code": "BGW",
      "lat": "33.3328",
      "lng": "44.3639",
      "name": "Al Muthana Airport",
      "city": "Baghdad",
      "state": "Baghdad",
      "country": "Iraq",
      "woeid": "12513890",
      "tz": "Asia/Baghdad",
      "phone": "",
      "type": "Other Airport",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "112",
      "icao": "",
      "direct_flights": "3",
      "carriers": "3"
    },
    {
      "code": "CTS",
      "lat": "42.7757",
      "lng": "141.691",
      "name": "New Chitose Airport",
      "city": "Chitose-shi",
      "state": "Hokkaido Prefecture",
      "country": "Japan",
      "woeid": "12523091",
      "tz": "Asia/Tokyo",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "87",
      "icao": "RJCC",
      "direct_flights": "30",
      "carriers": "28"
    },
    {
      "code": "DEZ",
      "lat": "35.2822",
      "lng": "40.1744",
      "name": "Deir Zzor Airport",
      "city": "Dayr az Zawr",
      "state": "Dayr az Zawr",
      "country": "Syria",
      "woeid": "12517699",
      "tz": "Asia/Damascus",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "700",
      "icao": "OSDZ",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "DNZ",
      "lat": "37.7667",
      "lng": "29.1",
      "name": "Cardak Airport",
      "city": "Denizli",
      "state": "Denizli",
      "country": "Turkey",
      "woeid": "12523098",
      "tz": "Europe/Istanbul",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "2792",
      "icao": "",
      "direct_flights": "2",
      "carriers": "1"
    },
    {
      "code": "ELQ",
      "lat": "26.3025",
      "lng": "43.7703",
      "name": "Gassim Airport",
      "city": "Al Qara'",
      "state": "Al Qasim",
      "country": "Saudi Arabia",
      "woeid": "12517334",
      "tz": "Asia/Riyadh",
      "phone": "+966(6)3800001",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "2126",
      "icao": "",
      "direct_flights": "4",
      "carriers": "2"
    },
    {
      "code": "ELU",
      "lat": "33.5122",
      "lng": "6.7842",
      "name": "Guemar Airport",
      "city": "El Oued",
      "state": "El Oued",
      "country": "Algeria",
      "woeid": "12510328",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "208",
      "icao": "",
      "direct_flights": "3",
      "carriers": "2"
    },
    {
      "code": "ERH",
      "lat": "31.9525",
      "lng": "-4.4067",
      "name": "Er Rachidia Airport",
      "city": "Errachidia",
      "state": "Er Rachidia",
      "country": "Morocco",
      "woeid": "12514786",
      "tz": "Africa/Casablanca",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "3392",
      "icao": "",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "GOM",
      "lat": "-1.6661",
      "lng": "29.2344",
      "name": "Goma International Airport",
      "city": "Goma",
      "state": "Democratic Republic of",
      "country": "Congo",
      "woeid": "12511956",
      "tz": "Africa/Lubumbashi",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "5089",
      "icao": "",
      "direct_flights": "2",
      "carriers": "4"
    },
    {
      "code": "HRG",
      "lat": "27.1858",
      "lng": "33.7981",
      "name": "Hurghada Airport",
      "city": "Bor Safajah",
      "state": "Al Bahr al Ahmar",
      "country": "Egypt",
      "woeid": "12512692",
      "tz": "Africa/Cairo",
      "phone": "+20 (0)65 442831",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "52",
      "icao": "HEGN",
      "direct_flights": "33",
      "carriers": "15"
    },
    {
      "code": "IAM",
      "lat": "28.0511",
      "lng": "9.6381",
      "name": "In Amenas Airport",
      "city": "Illizi",
      "state": "Illizi",
      "country": "Algeria",
      "woeid": "12510332",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "aeroport-iam@egsa-alger.com",
      "url": "http://www.egsa-alger.com/index.php?id=89",
      "runway_length": "9843",
      "elev": "1847",
      "icao": "",
      "direct_flights": "8",
      "carriers": "2"
    },
    {
      "code": "KBL",
      "lat": "34.5642",
      "lng": "69.2094",
      "name": "Kabul International Airport",
      "city": "Kabul",
      "state": "Kabul",
      "country": "Afghanistan",
      "woeid": "12510306",
      "tz": "Asia/Kabul",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "5871",
      "icao": "OAKB",
      "direct_flights": "19",
      "carriers": "9"
    },
    {
      "code": "KRT",
      "lat": "15.5917",
      "lng": "32.5533",
      "name": "Khartoum Airport",
      "city": "Khartoum",
      "state": "Al Khartum",
      "country": "Sudan",
      "woeid": "12517601",
      "tz": "Africa/Khartoum",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "1261",
      "icao": "",
      "direct_flights": "31",
      "carriers": "31"
    },
    {
      "code": "KVA",
      "lat": "40.915",
      "lng": "24.6203",
      "name": "Chrisoupolis Airport",
      "city": "Khrysoupolis",
      "state": "Anatoliki Makedonia",
      "country": "Greece",
      "woeid": "12513288",
      "tz": "Europe/Athens",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "18",
      "icao": "",
      "direct_flights": "8",
      "carriers": "5"
    },
    {
      "code": "LBV",
      "lat": "0.4592",
      "lng": "9.4153",
      "name": "Libreville Leon M Ba Airport",
      "city": "Libreville",
      "state": "Estuaire",
      "country": "Gabon",
      "woeid": "12512994",
      "tz": "Africa/Libreville",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "39",
      "icao": "FOOL",
      "direct_flights": "23",
      "carriers": "22"
    },
    {
      "code": "LDE",
      "lat": "43.1857",
      "lng": "0.00346",
      "name": "Ossun Airport",
      "city": "Juillan",
      "state": "Midi-Pyrenees",
      "country": "France",
      "woeid": "12512948",
      "tz": "Europe/Paris",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "1260",
      "icao": "LFBT",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "LFW",
      "lat": "6.1625",
      "lng": "1.255",
      "name": "Lome Tokoin Airport",
      "city": "Lome",
      "state": "Lome",
      "country": "Togo",
      "woeid": "12517850",
      "tz": "Africa/Lome",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "72",
      "icao": "DXXX",
      "direct_flights": "18",
      "carriers": "15"
    },
    {
      "code": "LXR",
      "lat": "25.675",
      "lng": "32.7075",
      "name": "Luxor Airport",
      "city": "Luxor",
      "state": "Qina",
      "country": "Egypt",
      "woeid": "12512697",
      "tz": "Africa/Cairo",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "288",
      "icao": "",
      "direct_flights": "16",
      "carriers": "13"
    },
    {
      "code": "LXS",
      "lat": "39.9214",
      "lng": "25.2417",
      "name": "Limnos Airport",
      "city": "Moudhros",
      "state": "Voreio Aigaio",
      "country": "Greece",
      "woeid": "12513307",
      "tz": "Europe/Athens",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "15",
      "icao": "",
      "direct_flights": "3",
      "carriers": "2"
    },
    {
      "code": "MAR",
      "lat": "10.5614",
      "lng": "-71.7253",
      "name": "La Chinita International Airport",
      "city": "Maracaibo",
      "state": "Zulia",
      "country": "Venezuela",
      "woeid": "12522800",
      "tz": "America/Caracas",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "235",
      "icao": "SVMC",
      "direct_flights": "8",
      "carriers": "9"
    },
    {
      "code": "MTY",
      "lat": "25.7783",
      "lng": "-100.107",
      "name": "Gen Mariano Escobedo International Airport",
      "city": "Pesquería",
      "state": "Nuevo Leon",
      "country": "Mexico",
      "woeid": "12514877",
      "tz": "America/Monterrey",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "1269",
      "icao": "MMMY",
      "direct_flights": "31",
      "carriers": "24"
    },
    {
      "code": "NKC",
      "lat": "18.0975",
      "lng": "-15.9478",
      "name": "Nouakchott Airport",
      "city": "Nouakchott",
      "state": "Nouakchott",
      "country": "Mauritania",
      "woeid": "12514806",
      "tz": "Africa/Nouakchott",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "7",
      "icao": "GQNN",
      "direct_flights": "10",
      "carriers": "8"
    },
    {
      "code": "OGX",
      "lat": "35.8764",
      "lng": "7.25695",
      "name": "Ain Beida",
      "city": "Ouargla",
      "state": "Oum el Bouaghi",
      "country": "Algeria",
      "woeid": "12805369",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "492",
      "icao": "",
      "direct_flights": "7",
      "carriers": "1"
    },
    {
      "code": "ORN",
      "lat": "35.6244",
      "lng": "-0.6186",
      "name": "Es Senia Airport",
      "city": "Oran Rp",
      "state": "Oran",
      "country": "Algeria",
      "woeid": "12510326",
      "tz": "Africa/Algiers",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "295",
      "icao": "",
      "direct_flights": "23",
      "carriers": "3"
    },
    {
      "code": "OUD",
      "lat": "34.7903",
      "lng": "-1.925",
      "name": "Angads Airport",
      "city": "Oujda",
      "state": "Oujda",
      "country": "Morocco",
      "woeid": "12514781",
      "tz": "Africa/Casablanca",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "1535",
      "icao": "GMFO",
      "direct_flights": "7",
      "carriers": "6"
    },
    {
      "code": "PHS",
      "lat": "16.7861",
      "lng": "100.278",
      "name": "Phitsanulok Airport",
      "city": "Phitsanulok",
      "state": "Phitsanulok",
      "country": "Thailand",
      "woeid": "12517774",
      "tz": "Asia/Bangkok",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "145",
      "icao": "",
      "direct_flights": "1",
      "carriers": "1"
    },
    {
      "code": "RIY",
      "lat": "14.6611",
      "lng": "49.3761",
      "name": "Riyan Airport",
      "city": "Shuhayr",
      "state": "Hadramawt",
      "country": "Yemen",
      "woeid": "12523004",
      "tz": "Asia/Aden",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9843",
      "elev": "54",
      "icao": "",
      "direct_flights": "7",
      "carriers": "3"
    }
  ]
  